# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 8
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        build-scan-publish: true
        build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
        build-scan-terms-of-use-agree: "yes"
        validate-wrappers: true
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Set up Gradle build
      run: ./gradlew setupCIWorkspace
    - name: Build with Gradle
      run: ./gradlew build
    - name: Copy artifacts to a single directory
      run: |
        mkdir build/tmp/ci -p
        mkdir build/tmp/ci-dev -p
        mkdir build/tmp/ci-sources -p
        cp module-*/build/libs/* build/tmp/ci
        mv build/tmp/ci/*-all-*-dev.jar build/tmp/ci-dev
        mv build/tmp/ci/*-compat-*-dev.jar build/tmp/ci-dev
        rm build/tmp/ci/*-dev.jar
        mv build/tmp/ci-dev/* build/tmp/ci
        rm build/tmp/ci/*-common-*.jar
        mv build/tmp/ci/*-sources.jar build/tmp/ci-sources
    - uses: actions/upload-artifact@v4
      with:
        name: Package
        path: build/tmp/ci
    - uses: actions/upload-artifact@v4
      with:
        name: Package-sources
        path: build/tmp/ci-sources
